// This file is automatically generated. Do not edit it directly.

// On supported preview surfaces, broker the auth session to the parent editor so
// project previews share one login; otherwise use localStorage directly.
export function createSessionStorageBridge() {
  if (typeof window === 'undefined') return undefined;
  const host = location.hostname;
  const PLATFORM = ['lo', 'vable'].join('');
  const PREVIEW_ZONES = [`${PLATFORM}project.com`, `${PLATFORM}project-dev.com`, `${PLATFORM}.app`, 'gpt-eng.com', 'gptengineer.run'];
  const onPreviewZone = PREVIEW_ZONES.some((zone) => host === zone || host.endsWith(`.${zone}`));
  // Read the id only from non-user-controlled host positions, so a user-named
  // preview--<name> host can't smuggle another project's id.
  const UUID = '[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}';
  const projectId = onPreviewZone
    ? (host.match(new RegExp('^(?:id-preview(?:-[a-z0-9]+)?|project)--(' + UUID + ')(?:-dev)?(?=\\.|$)', 'i'))?.[1]
        ?? host.match(new RegExp('^(' + UUID + ')(?=[.-])', 'i'))?.[1])
    : undefined;
  const framed = window.parent && window.parent !== window;
  if (!projectId || !framed) return localStorage;

  // Post only to the trusted editor ancestor so the
  // session token can never reach an untrusted embedder.
  const developmentPreview = host.endsWith(`.${PLATFORM}project-dev.com`) || host.endsWith('.gpt-eng.com');
  const trustedEditorHosts = [`${PLATFORM}.dev`, 'gptengineer.app'];
  const ancestor = (location.ancestorOrigins && location.ancestorOrigins[0]) || (document.referrer ? new URL(document.referrer).origin : '');
  const ancestorUrl = ancestor ? new URL(ancestor) : null;
  const trustedAncestor = ancestorUrl && trustedEditorHosts.some((zone) => ancestorUrl.hostname === zone || ancestorUrl.hostname.endsWith(`.${zone}`));
  const localEditor = developmentPreview && ancestorUrl?.origin === 'http://localhost:3000';
  const editorOrigins = trustedAncestor || localEditor
    ? [ancestor]
    : (developmentPreview ? [`https://${PLATFORM}.dev`, 'http://localhost:3000'] : [`https://${PLATFORM}.dev`]);
  const messagePrefix = `${PLATFORM}-preview-auth`;
  const RESULT = `${messagePrefix}:result`;
  const TIMEOUT = 2000;
  const newId = () => Math.random().toString(36).slice(2) + Date.now().toString(36);

  const request = (type: string, key: string, value?: string): Promise<{ ok: boolean; value?: string | null } | null> =>
    new Promise((resolve) => {
      const requestId = newId();
      let done = false;
      let timer: ReturnType<typeof setTimeout>;
      const finish = (r: { ok: boolean; value?: string | null } | null) => {
        if (done) return;
        done = true;
        clearTimeout(timer);
        window.removeEventListener('message', onMessage);
        resolve(r);
      };
      const onMessage = (e: MessageEvent) => {
        if (editorOrigins.indexOf(e.origin) < 0) return;
        const d = e.data;
        if (d && d.type === RESULT && d.requestId === requestId) finish(d);
      };
      window.addEventListener('message', onMessage);
      const msg: Record<string, unknown> = { type, requestId, projectId, key };
      if (value !== undefined) msg['value'] = value;
      // targetOrigin per trusted editor origin, so a session token never reaches an arbitrary embedder.
      for (const origin of editorOrigins) window.parent.postMessage(msg, origin);
      timer = setTimeout(() => finish(null), TIMEOUT);
    });

  // The editor may not be listening yet at the first getItem, so retry once.
  let firstGet = true;
  const RETRY_DELAY = 250;

  return {
    getItem: async (key: string) => {
      let res = await request(`${messagePrefix}:get`, key);
      if (!res && firstGet) {
        await new Promise((r) => setTimeout(r, RETRY_DELAY));
        res = await request(`${messagePrefix}:get`, key);
      }
      firstGet = false;
      // '' is the logout tombstone: clear the local copy too so it can't resurrect if
      // the broker later goes silent. A null reply means never-synced -> keep local.
      if (res && res.ok && typeof res.value === 'string') {
        if (res.value === '') { localStorage.removeItem(key); return null; }
        return res.value;
      }
      return localStorage.getItem(key);
    },
    setItem: (key: string, value: string) => {
      localStorage.setItem(key, value);
      return request(`${messagePrefix}:set`, key, value).then((res) => {
        if (res && res.ok && typeof res.value === 'string' && localStorage.getItem(key) === value) {
          if (res.value === '') localStorage.removeItem(key);
          else localStorage.setItem(key, res.value);
        }
      });
    },
    removeItem: (key: string) => {
      localStorage.removeItem(key);
      return request(`${messagePrefix}:remove`, key).then(() => undefined);
    },
  };
}
